[project]
name = "copilot-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-contentsafety>=1.0.0",
    "mcp[cli]>=1.12.4",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
